name: deploy portfolio website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<637423389066>:role/CICDROLL
          aws-region: ap-south-1
          name: Upload Website to S3

          run: aws s3 sync website/ s3://portifolio-s3-website-bucket --delete
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1C6XXZN65ZEWE \
            --paths "/*"